version: '3.3'

services:
  db_migrator:
    image: ghcr.io/mehmet-d02/pusula_healthcare_migration:${TAG}
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__Default=Host=postgresdb;Port=5432;Database=HealthCare;User ID=postgres;Password=post1tepas0225.;
    networks:
      - healthcare_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        max_attempts: 3  
    depends_on:
      - postgresdb

networks:
  healthcare_network:
    external: true

