version: '3.3'
services:
  kibana:
    image: kibana:8.15.0
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=zqhp3x.5
      - XPACK_MONITORING_ENABLED=true
      - XPACK_MONITORING_COLLECTION_ENABLED=true
      - LOGGING_VERBOSE=true
    ports:
      - "5601:5601"
    networks:
      - healthcare_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker  

networks:
  healthcare_network:
    external: true
