global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'Team1-Node1'
    static_configs:
      - targets: ['node_exporter_node1:9100']
  - job_name: 'Team1-Node2'
    static_configs:
      - targets: ['node_exporter_node2:9100']




