version: '3.3'
services:
  pusula_healthcare:
    image: ghcr.io/mehmet-d02/pusula_healthcare:${TAG}
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_HTTP_PORTS=80
    networks:
      - healthcare_network
    depends_on:
      - postgresdb
      - redis
      - rabbitmq
      - elasticsearch
    deploy:
      replicas: 4
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.pusula_healthcare.rule=Host(`team1-pusula-healthcare.pusulayazilim.com.tr`)"
        - "traefik.http.services.pusula_healthcare.loadbalancer.server.port=80"
        - "traefik.http.services.pusula_healthcare.loadbalancer.sticky.cookie=true"
        - "traefik.http.services.pusula_healthcare.loadbalancer.sticky.cookie.name=pulsula_healthcare_session"
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: on-failure

networks:
  healthcare_network:
    external: true
