version: '3.3'

services:
  rabbitmq-node1:
    image: rabbitmq:management
    hostname: rabbitmq-node1
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=team1
      - RABBITMQ_DEFAULT_PASS=rabPass23452.
      - RABBITMQ_ERLANG_COOKIE=my-erlang-cookie
    volumes:
      - rabbitmq-data-node1:/var/lib/rabbitmq
    networks:
      - healthcare_network
    deploy:
      placement:
        constraints:
          - node.role == manager

  rabbitmq-node2:
    image: rabbitmq:management
    hostname: rabbitmq-node2
    restart: always
    ports:
      - "15673:15672"
      - "5673:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=team1
      - RABBITMQ_DEFAULT_PASS=rabPass23452.
      - RABBITMQ_ERLANG_COOKIE=my-erlang-cookie
      - RABBITMQ_NODENAME=rabbit@rabbitmq-node2
      - RABBITMQ_CLUSTER_NODE=rabbit@rabbitmq-node1
    volumes:
      - rabbitmq-data-node2:/var/lib/rabbitmq
    networks:
      - healthcare_network
    deploy:
      placement:
        constraints:
          - node.role == worker

  rabbitmq-node3:
    image: rabbitmq:management
    hostname: rabbitmq-node3
    restart: always
    ports:
      - "15674:15672"
      - "5674:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=team1
      - RABBITMQ_DEFAULT_PASS=rabPass23452.
      - RABBITMQ_ERLANG_COOKIE=my-erlang-cookie
      - RABBITMQ_NODENAME=rabbit@rabbitmq-node3
      - RABBITMQ_CLUSTER_NODE=rabbit@rabbitmq-node1
    volumes:
      - rabbitmq-data-node3:/var/lib/rabbitmq
    networks:
      - healthcare_network
    deploy:
      placement:
        constraints:
          - node.role == worker

volumes:
  rabbitmq-data-node1:
  rabbitmq-data-node2:
  rabbitmq-data-node3:

networks:
  healthcare_network:
    external: true

