version: '3.3'

services:
  sonarqube:
    image: sonarqube:latest
    restart: always
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgresdb:5432/sonarqube_db
      SONAR_JDBC_USERNAME: postgres
      SONAR_JDBC_PASSWORD: post1tepas0225.
      SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"
      TZ: Europe/Istanbul
    ports:
      - "9100:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - healthcare_network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:

networks:
  healthcare_network:
    external: true
