version: '3.3'
services:
  traefik:
    image: traefik:v2.10
    command:
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.watch=true"
      - "--entrypoints.web.address=:8085"  
      - "--entrypoints.dashboard.address=:8086"  
      - "--api.insecure=true"
      - "--log.level=DEBUG"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "8085:8085"  
      - "8086:8080" 
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - healthcare_network
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager

networks:
  healthcare_network:
    external: true


