version: '3.3'
services:
  elasticsearch:
    image: elasticsearch:8.15.0
    restart: always
    environment:
      - xpack.watcher.enabled=false
      - xpack.security.enabled=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=zqhp3x.5
    ports:
      - "9200:9200"
    volumes:
      - pthesdata:/usr/share/elasticsearch/data
    networks:
      - healthcare_network
    deploy:
      replicas: 1

volumes:
  pthesdata:

networks:
  healthcare_network:
    external: true
