version: '3.3'
services:
  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: training@pusulayazilim.com.tr
      PGADMIN_DEFAULT_PASSWORD: myPassw0rd
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:5050"
    volumes:
      - pthpgadmin4data:/var/lib/pgadmin
    networks:
      - healthcare_network
    deploy:
      replicas: 1

volumes:
  pthpgadmin4data:

networks:
  healthcare_network:
    external: true
