version: '3.3'
services:
  postgresdb:
    image: postgres
    restart: always
    volumes:
      - pthpostgresdata:/var/lib/postgresql/data
    command: postgres -c 'max_connections=250'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: post1tepas0225.
      POSTGRES_DB: test_db
      TZ: Europe/Istanbul
    ports:
      - "5432:5432"
    networks:
      - healthcare_network
    deploy:
      replicas: 1

volumes:
  pthpostgresdata:

networks:
  healthcare_network:
    external: true
