version: '3.3'
services:
  rabbitmq:
    image: rabbitmq:management
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=team1
      - RABBITMQ_DEFAULT_PASS=rabPass23452.
    volumes:
      - pthrabbitmqdata:/var/lib/rabbitmq
    networks:
      - healthcare_network
    deploy:
      replicas: 1

volumes:
  pthrabbitmqdata:

networks:
  healthcare_network:
    external: true


