version: '3.3'
services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - pthredisdata:/data
    networks:
      - healthcare_network
    deploy:
      replicas: 1
    environment:
      - REDIS_PASSWORD=rdi8725a.
    command: ["redis-server", "--requirepass", "rdi8725a."]

volumes:
  pthredisdata:

networks:
  healthcare_network:
    external: true
